/*******************************************************************************
 * Copyright 2017-2026 TAXTELECOM, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package org.pgcodekeeper.core.it.difftree;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.pgcodekeeper.core.TestUtils;
import org.pgcodekeeper.core.api.PgCodeKeeperApi;
import org.pgcodekeeper.core.database.api.IDatabaseProvider;
import org.pgcodekeeper.core.database.api.schema.DbObjType;
import org.pgcodekeeper.core.database.api.schema.IDatabase;
import org.pgcodekeeper.core.database.api.schema.ISequence;
import org.pgcodekeeper.core.database.api.schema.ObjectReference;
import org.pgcodekeeper.core.database.ms.MsDatabaseProvider;
import org.pgcodekeeper.core.database.pg.PgDatabaseProvider;
import org.pgcodekeeper.core.model.difftree.DiffTree;
import org.pgcodekeeper.core.model.difftree.TreeElement;
import org.pgcodekeeper.core.settings.CoreSettings;

/**
 * The cache of a sequence is a difference like any other, until the operator
 * says it is not.
 * <p>
 * {@code ISettings.isIgnoreSequenceCache} takes the cache out of the comparison
 * and out of the {@code ALTER} that follows from it, and out of nothing else: a
 * sequence created by the migration is still created with the cache written in
 * the project, on its own and as the identity of a column alike, because that
 * cache is the one deliberate statement the project makes about it.
 * <p>
 * Every case below states both what the comparison reports and, byte for byte,
 * the script that follows from it, and every one of them is asked twice, with
 * the setting off and on, so that what the setting changes is exactly what is
 * written down here.
 */
class SequenceCacheComparisonTest {

    private static final String SEQUENCE_CACHE_1 = """
            CREATE SEQUENCE public.s
            \tSTART WITH 1
            \tINCREMENT BY 1
            \tNO MAXVALUE
            \tNO MINVALUE
            \tCACHE 1;""";

    private static final String SEQUENCE_CACHE_10 = """
            CREATE SEQUENCE public.s
            \tSTART WITH 1
            \tINCREMENT BY 1
            \tNO MAXVALUE
            \tNO MINVALUE
            \tCACHE 10;""";

    private static final String SEQUENCE_CACHE_10_INCREMENT_2 = """
            CREATE SEQUENCE public.s
            \tSTART WITH 1
            \tINCREMENT BY 2
            \tNO MAXVALUE
            \tNO MINVALUE
            \tCACHE 10;""";

    private static final String IDENTITY_CACHE_1 = """
            CREATE TABLE public.t (
                id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq
                    START WITH 1
                    INCREMENT BY 1
                    NO MAXVALUE
                    NO MINVALUE
                    CACHE 1)
            );""";

    private static final String IDENTITY_CACHE_10 = """
            CREATE TABLE public.t (
                id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq
                    START WITH 1
                    INCREMENT BY 1
                    NO MAXVALUE
                    NO MINVALUE
                    CACHE 10)
            );""";

    private static final String IDENTITY_CACHE_10_MAXVALUE = """
            CREATE TABLE public.t (
                id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq
                    START WITH 1
                    INCREMENT BY 1
                    MAXVALUE 500
                    NO MINVALUE
                    CACHE 10)
            );""";

    private static final String MS_SEQUENCE_CACHE_1 = """
            CREATE SEQUENCE [dbo].[s]
            \tAS [bigint]
            \tSTART WITH 1
            \tINCREMENT BY 1
            \tMINVALUE 1
            \tMAXVALUE 100
            \tCACHE 1
            GO""";

    private static final String MS_SEQUENCE_CACHE_10 = """
            CREATE SEQUENCE [dbo].[s]
            \tAS [bigint]
            \tSTART WITH 1
            \tINCREMENT BY 1
            \tMINVALUE 1
            \tMAXVALUE 100
            \tCACHE 10
            GO""";

    private static final String MS_SEQUENCE_CACHE_10_MAXVALUE = """
            CREATE SEQUENCE [dbo].[s]
            \tAS [bigint]
            \tSTART WITH 1
            \tINCREMENT BY 1
            \tMINVALUE 1
            \tMAXVALUE 500
            \tCACHE 10
            GO""";

    private final PgDatabaseProvider provider = new PgDatabaseProvider();
    private final MsDatabaseProvider msProvider = new MsDatabaseProvider();

    // a sequence of its own

    @Test
    void cacheAloneIsADifferenceWhileTheSettingIsOff() throws IOException, InterruptedException {
        assertDiffers(provider, SEQUENCE_CACHE_1, SEQUENCE_CACHE_10, settings(false), "s", """
                SET search_path = pg_catalog;

                ALTER SEQUENCE public.s
                \tCACHE 10;""");
    }

    @Test
    void cacheAloneIsNoDifferenceWhileTheSettingIsOn() throws IOException, InterruptedException {
        assertNoDifference(provider, SEQUENCE_CACHE_1, SEQUENCE_CACHE_10, settings(true));
    }

    /**
     * The heart of the matter: a sequence that differs in the cache and in one
     * more thing keeps its place in the diff and is migrated in full, minus the
     * cache and nothing else.
     */
    @Test
    void aDifferenceBesideTheCacheIsMigratedWithoutTheCache() throws IOException, InterruptedException {
        assertDiffers(provider, SEQUENCE_CACHE_1, SEQUENCE_CACHE_10_INCREMENT_2, settings(true), "s", """
                SET search_path = pg_catalog;

                ALTER SEQUENCE public.s
                \tINCREMENT BY 2;""");
    }

    @Test
    void theSameDifferenceCarriesTheCacheWhileTheSettingIsOff() throws IOException, InterruptedException {
        assertDiffers(provider, SEQUENCE_CACHE_1, SEQUENCE_CACHE_10_INCREMENT_2, settings(false), "s", """
                SET search_path = pg_catalog;

                ALTER SEQUENCE public.s
                \tINCREMENT BY 2
                \tCACHE 10;""");
    }

    // the identity sequence of a column, which is a part of the state of its table

    @Test
    void identityCacheAloneIsADifferenceWhileTheSettingIsOff() throws IOException, InterruptedException {
        assertDiffers(provider, IDENTITY_CACHE_1, IDENTITY_CACHE_10, settings(false), "t", """
                SET search_path = pg_catalog;

                ALTER SEQUENCE public.t_id_seq
                \tCACHE 10;""");
    }

    @Test
    void identityCacheAloneIsNoDifferenceWhileTheSettingIsOn() throws IOException, InterruptedException {
        assertNoDifference(provider, IDENTITY_CACHE_1, IDENTITY_CACHE_10, settings(true));
    }

    @Test
    void anIdentityDifferenceBesideTheCacheIsMigratedWithoutTheCache() throws IOException, InterruptedException {
        assertDiffers(provider, IDENTITY_CACHE_1, IDENTITY_CACHE_10_MAXVALUE, settings(true), "t", """
                SET search_path = pg_catalog;

                ALTER SEQUENCE public.t_id_seq
                \tMAXVALUE 500;""");
    }

    @Test
    void theSameIdentityDifferenceCarriesTheCacheWhileTheSettingIsOff() throws IOException, InterruptedException {
        assertDiffers(provider, IDENTITY_CACHE_1, IDENTITY_CACHE_10_MAXVALUE, settings(false), "t", """
                SET search_path = pg_catalog;

                ALTER SEQUENCE public.t_id_seq
                \tMAXVALUE 500
                \tCACHE 10;""");
    }

    /**
     * The identity of a column whose table is being created is written into the
     * body of that creation, wrapped in a {@code DO} block when the settings ask
     * for the existence check. That is a creation, so the cache of the project
     * is written there whatever the setting says.
     */
    @Test
    void aCreatedIdentityKeepsTheProjectCache() throws IOException, InterruptedException {
        String expected = """
                SET search_path = pg_catalog;

                CREATE TABLE public.t (
                \tid bigint
                );

                DO $$
                BEGIN
                \tALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
                \t\tSEQUENCE NAME public.t_id_seq
                \t\tSTART WITH 1
                \t\tINCREMENT BY 1
                \t\tNO MAXVALUE
                \t\tNO MINVALUE
                \t\tCACHE 10
                \t);
                EXCEPTION WHEN OTHERS THEN
                \tIF (SQLSTATE = '42P07') THEN
                \t\tRAISE NOTICE '%, skip', SQLERRM;
                \tELSE
                \t\tRAISE;
                \tEND IF;
                END; $$
                LANGUAGE 'plpgsql';""";

        for (boolean ignoreCache : new boolean[] { false, true }) {
            CoreSettings settings = settings(ignoreCache);
            settings.setGenerateExistDoBlock(true);
            assertDiffers(provider, "", IDENTITY_CACHE_10, settings, "t", expected);
        }
    }

    /**
     * A sequence of its own is created the same way, cache included.
     */
    @Test
    void aCreatedSequenceKeepsTheProjectCache() throws IOException, InterruptedException {
        String expected = """
                SET search_path = pg_catalog;

                CREATE SEQUENCE public.s
                \tSTART WITH 1
                \tINCREMENT BY 1
                \tNO MAXVALUE
                \tNO MINVALUE
                \tCACHE 10;""";

        for (boolean ignoreCache : new boolean[] { false, true }) {
            assertDiffers(provider, "", SEQUENCE_CACHE_10, settings(ignoreCache), "s", expected);
        }
    }

    // MS SQL, where the cache is the clause CACHE [n] | NO CACHE as a whole

    @Test
    void msCacheAloneIsADifferenceWhileTheSettingIsOff() throws IOException, InterruptedException {
        assertDiffers(msProvider, MS_SEQUENCE_CACHE_1, MS_SEQUENCE_CACHE_10, settings(false), "s", """
                ALTER SEQUENCE [dbo].[s]
                \tCACHE 10
                GO""");
    }

    @Test
    void msCacheAloneIsNoDifferenceWhileTheSettingIsOn() throws IOException, InterruptedException {
        assertNoDifference(msProvider, MS_SEQUENCE_CACHE_1, MS_SEQUENCE_CACHE_10, settings(true));
    }

    @Test
    void anMsDifferenceBesideTheCacheIsMigratedWithoutTheCache() throws IOException, InterruptedException {
        assertDiffers(msProvider, MS_SEQUENCE_CACHE_1, MS_SEQUENCE_CACHE_10_MAXVALUE, settings(true), "s", """
                ALTER SEQUENCE [dbo].[s]
                \tMAXVALUE 500
                GO""");
    }

    @Test
    void theSameMsDifferenceCarriesTheCacheWhileTheSettingIsOff() throws IOException, InterruptedException {
        assertDiffers(msProvider, MS_SEQUENCE_CACHE_1, MS_SEQUENCE_CACHE_10_MAXVALUE, settings(false), "s", """
                ALTER SEQUENCE [dbo].[s]
                \tMAXVALUE 500
                \tCACHE 10
                GO""");
    }

    /**
     * The relaxation lives beside {@code equals}, never inside it: the two
     * states are still unequal and still hash differently, so equality and hash
     * keep agreeing with each other, and a caller that has not asked for the
     * relaxation sees nothing of it. The relaxed comparison carries a hash
     * relaxed in exactly the same one place, which is what makes it as safe as
     * the plain one - a comparison relaxed alone would call two objects equal
     * that the hash still tells apart, the very failure
     * {@code PgConstraintFk.compareUnalterable} once produced.
     */
    @Test
    void theRelaxationStaysOutOfEqualsAndHashCode() throws IOException, InterruptedException {
        CoreSettings settings = settings(true);
        for (IDatabaseProvider each : List.of(provider, msProvider)) {
            boolean isPg = each == provider;
            ISequence one = sequence(each, load(each, isPg ? SEQUENCE_CACHE_1 : MS_SEQUENCE_CACHE_1, settings));
            ISequence other = sequence(each, load(each, isPg ? SEQUENCE_CACHE_10 : MS_SEQUENCE_CACHE_10, settings));

            assertNotEquals(one, other, "the two states are not equal, only equal up to their cache");
            assertNotEquals(one.hashCode(), other.hashCode(), "the hash must keep telling them apart");
            assertTrue(one.compareIgnoringCache(other), "and must be equal once the cache is left out");
            assertEquals(one.hashIgnoringCache(), other.hashIgnoringCache(),
                    "the guard of that comparison must be relaxed in the same one place");

            ISequence beyondTheCache = sequence(each,
                    load(each, isPg ? SEQUENCE_CACHE_10_INCREMENT_2 : MS_SEQUENCE_CACHE_10_MAXVALUE, settings));
            assertEquals(false, one.compareIgnoringCache(beyondTheCache),
                    "a difference beyond the cache is still a difference");
            assertNotEquals(one.hashIgnoringCache(), beyondTheCache.hashIgnoringCache(),
                    "and the relaxed hash must tell it apart as well");
        }
    }

    private static CoreSettings settings(boolean ignoreSequenceCache) {
        CoreSettings settings = new CoreSettings();
        settings.setIgnoreSequenceCache(ignoreSequenceCache);
        return settings;
    }

    private void assertNoDifference(IDatabaseProvider each, String oldSql, String newSql, CoreSettings settings)
            throws IOException, InterruptedException {
        IDatabase oldDb = load(each, oldSql, settings);
        IDatabase newDb = load(each, newSql, settings);

        assertEquals(List.of(), changedNames(DiffTree.create(settings, oldDb, newDb)),
                "a cache the settings ignore is not a difference");
        assertScriptIs("", PgCodeKeeperApi.diff(each, oldDb, newDb, settings));
    }

    private void assertDiffers(IDatabaseProvider each, String oldSql, String newSql, CoreSettings settings,
                               String changed, String expectedScript) throws IOException, InterruptedException {
        IDatabase oldDb = load(each, oldSql, settings);
        IDatabase newDb = load(each, newSql, settings);

        assertEquals(List.of(changed), changedNames(DiffTree.create(settings, oldDb, newDb)),
                "a migratable difference must stay in the diff tree");
        assertScriptIs(expectedScript, PgCodeKeeperApi.diff(each, oldDb, newDb, settings));
    }

    private static void assertScriptIs(String expected, String actual) {
        assertArrayEquals(expected.getBytes(StandardCharsets.UTF_8), actual.trim().getBytes(StandardCharsets.UTF_8),
                () -> "script must be byte for byte:\nexpected\n" + expected + "\nactual\n" + actual);
    }

    private static ISequence sequence(IDatabaseProvider each, IDatabase database) {
        String schema = each instanceof PgDatabaseProvider ? "public" : "dbo";
        ISequence sequence = (ISequence) database.getStatement(
                new ObjectReference(schema, "s", DbObjType.SEQUENCE));
        assertNotNull(sequence, "fixture must define the sequence");
        return sequence;
    }

    /**
     * @return the names of the tables and sequences the tree reports as changed
     */
    private static List<String> changedNames(TreeElement root) {
        List<String> names = new ArrayList<>();
        collectChanged(root, names);
        return names;
    }

    private static void collectChanged(TreeElement el, List<String> names) {
        if (el.getType() == DbObjType.TABLE || el.getType() == DbObjType.SEQUENCE) {
            names.add(el.getName());
        }
        for (TreeElement child : el.getChildren()) {
            collectChanged(child, names);
        }
    }

    private IDatabase load(IDatabaseProvider each, String sql, CoreSettings settings)
            throws IOException, InterruptedException {
        settings.clearErrors();
        IDatabase database = each.getDumpLoader(
                        () -> new ByteArrayInputStream(sql.getBytes(StandardCharsets.UTF_8)),
                        "test/" + getClass().getName(), settings)
                .load();
        TestUtils.assertErrors(settings.getErrors());
        return database;
    }
}
