/*******************************************************************************
 * Copyright 2017-2026 TAXTELECOM, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package org.pgcodekeeper.core.database.pg.parser.statement;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.IOException;

import org.junit.jupiter.api.Test;
import org.pgcodekeeper.core.api.PgCodeKeeperApi;
import org.pgcodekeeper.core.database.pg.PgDatabaseProvider;
import org.pgcodekeeper.core.database.pg.loader.PgDumpLoader;
import org.pgcodekeeper.core.database.pg.schema.PgAbstractTable;
import org.pgcodekeeper.core.database.pg.schema.PgColumn;
import org.pgcodekeeper.core.database.pg.schema.PgDatabase;
import org.pgcodekeeper.core.database.pg.schema.PgSchema;
import org.pgcodekeeper.core.settings.CoreSettings;

/**
 * The six alternatives of {@code column_action} that state a property of the
 * column rather than its content: {@code SET EXPRESSION},
 * {@code DROP EXPRESSION}, {@code DROP IDENTITY}, {@code alter_identity},
 * {@code SET COMPRESSION} and the Greenplum {@code SET ENCODING}. All six parsed
 * and reached no writer.
 *
 * <p>
 * The column's counterpart to {@link PgAlterTablePropertyTest}, and the third
 * pass over the identity after the sequence name it is created with
 * ({@code PgAlterTableLegalDdlTest}) and the type it is retyped with
 * ({@link PgAlterTableColumnTest}).
 *
 * <p>
 * Measured before the fix, none of the six was merely dropped - each made the
 * tool write the state the file had just left, and three of them wrote it by
 * destroying the column:
 *
 * <ul>
 * <li>{@code SET EXPRESSION} and {@code DROP EXPRESSION}: {@code DROP COLUMN c1}
 * followed by an {@code ADD COLUMN} carrying the <i>old</i> expression;
 * <li>{@code DROP IDENTITY}: {@code ALTER COLUMN c1 ADD GENERATED ALWAYS AS
 * IDENTITY}, putting back the identity the file had removed;
 * <li>{@code SET GENERATED BY DEFAULT}: {@code SET GENERATED ALWAYS}, the
 * opposite of what the file says;
 * <li>{@code SET INCREMENT BY 5}: {@code ALTER SEQUENCE ... INCREMENT BY 1};
 * <li>{@code SET COMPRESSION lz4}: {@code SET COMPRESSION DEFAULT};
 * <li>{@code SET ENCODING (...)}: a {@code DROP COLUMN} / {@code ADD COLUMN}
 * pair.
 * </ul>
 */
class PgAlterTableColumnPropertyTest {

    private static final String SCHEMA = "public";
    private static final String TABLE = "t";

    // ------------------------------------------------------- SET EXPRESSION

    /**
     * The defect, stated directly: a project file that restates the expression of
     * a generated column must have that expression reach the database. Unread,
     * the model kept the expression the {@code CREATE} declared, and because a
     * generated column cannot be altered in place the tool proposed dropping the
     * column and adding it back with the old expression.
     */
    @Test
    void anExpressionStatedByAlterReachesTheModel() throws Exception {
        PgDatabase byAlter = load(generated("(c0 * 2)") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET EXPRESSION AS ((c0 * 3));""");
        assertEquals("(c0 * 3)", columnOf(byAlter, "c1").getDefaultValue(),
                "the expression the file states must be the one the model carries");

        String script = pipeline(load(generated("(c0 * 3)")), byAlter);
        assertEquals("", script.trim(),
                () -> "an expression written by ALTER must build the same column, got:\n" + script);
    }

    /**
     * The other direction, and the one the empty script cannot speak for on its
     * own: against a database carrying the old expression, the file must produce
     * the change. A generated column has no in-place alter -
     * {@code PgColumn.isGeneratedColumnChanged} recreates on any change of the
     * expression - so the pair is what the change looks like.
     */
    @Test
    void anExpressionStatedByAlterReachesTheDatabase() throws Exception {
        String script = pipeline(load(generated("(c0 * 2)")),
                load(generated("(c0 * 2)") + """

                        ALTER TABLE public.t ALTER COLUMN c1 SET EXPRESSION AS ((c0 * 3));"""));
        assertEquals("""
                SET search_path = pg_catalog;

                ALTER TABLE ONLY public.t
                \tDROP COLUMN c1;

                ALTER TABLE public.t
                \tADD COLUMN c1 integer GENERATED ALWAYS AS ((c0 * 3)) STORED;""", script.trim());
    }

    /**
     * Both halves of the expression are filled, the normalized one included. An
     * expression is compared through its normalized half alone, so a branch that
     * filled only the raw one would make every column it touched read as changed
     * against the identical column written inline - and, the normalized half
     * being empty, equal to a column with no expression at all.
     *
     * <p>
     * The fixture is deliberately not written canonically: the two spellings
     * differ in spacing, so raw equality cannot carry this assertion.
     *
     * <p>
     * And the other side of the same rule, which the comparison cannot speak
     * for: the raw half keeps the author's own spelling, because that is the
     * text the DDL is written from and a project file has to round-trip as its
     * author wrote it.
     */
    @Test
    void bothHalvesOfTheExpressionAreFilled() throws Exception {
        PgDatabase byAlter = load(generated("(c0 * 2)") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET EXPRESSION AS ((c0   *   3));""");
        PgDatabase inline = load(generated("(c0 * 3)"));

        assertTrue(columnOf(inline, "c1").compare(columnOf(byAlter, "c1")),
                "a re-spaced expression must compare as one expression, which is the normalized half");
        assertEquals("c1 integer GENERATED ALWAYS AS ((c0   *   3)) STORED",
                columnOf(byAlter, "c1").getFullDefinition(),
                "and the DDL must carry the author's own spelling, which is the raw half");
    }

    /**
     * The one column the statement does not speak for. PostgreSQL refuses it on a
     * column that is not generated, so a file saying it is illegal DDL and the
     * model's answer to it is the server's - the same reading
     * {@code ALTER COLUMN ... DROP DEFAULT} already gets on a generated column.
     */
    @Test
    void anExpressionSetOnAPlainColumnIsLeftAlone() throws Exception {
        PgDatabase db = load(table("c0 integer,\n\tc1 integer DEFAULT 1") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET EXPRESSION AS ((c0 * 3));""");
        assertEquals("1", columnOf(db, "c1").getDefaultValue(),
                "a column that is not generated has no expression for this statement to set");
    }

    // ------------------------------------------------------ DROP EXPRESSION

    /**
     * The statement that turns a generated column into an ordinary one. Both the
     * generation option and the expression have to go: they live in two fields
     * and the expression shares its field with a plain {@code DEFAULT}, so a
     * branch clearing only the option would leave the column carrying the
     * generation expression as its default.
     */
    @Test
    void aDroppedExpressionMakesTheColumnPlain() throws Exception {
        PgDatabase byAlter = load(generated("(c0 * 2)") + """

                ALTER TABLE public.t ALTER COLUMN c1 DROP EXPRESSION;""");
        PgColumn col = columnOf(byAlter, "c1");
        assertFalse(col.isGenerated(), "the column must stop being a generated one");
        assertNull(col.getDefaultValue(),
                "and the expression must go with it, or it stays behind as a plain DEFAULT");

        String script = pipeline(load(table("c0 integer,\n\tc1 integer")), byAlter);
        assertEquals("", script.trim(),
                () -> "a column whose expression the file drops must equal a plain one, got:\n" + script);
    }

    /** The other direction: against a database that still generates the column. */
    @Test
    void aDroppedExpressionReachesTheDatabase() throws Exception {
        String script = pipeline(load(generated("(c0 * 2)")),
                load(generated("(c0 * 2)") + """

                        ALTER TABLE public.t ALTER COLUMN c1 DROP EXPRESSION;"""));
        assertEquals("""
                SET search_path = pg_catalog;

                ALTER TABLE ONLY public.t
                \tDROP COLUMN c1;

                ALTER TABLE public.t
                \tADD COLUMN c1 integer;""", script.trim());
    }

    /**
     * And the column this statement does not speak for either. The server refuses
     * it on a column that is not generated, so the plain {@code DEFAULT} sharing
     * that field must survive - clearing it would take away a value no statement
     * in the file asked to lose.
     */
    @Test
    void aDroppedExpressionLeavesAPlainDefaultAlone() throws Exception {
        PgDatabase db = load(table("c0 integer,\n\tc1 integer DEFAULT 1") + """

                ALTER TABLE public.t ALTER COLUMN c1 DROP EXPRESSION IF EXISTS;""");
        assertEquals("1", columnOf(db, "c1").getDefaultValue(),
                "a plain DEFAULT is not a generation expression this statement may drop");
    }

    // -------------------------------------------------------- DROP IDENTITY

    /**
     * A dropped identity must leave the model whole: the kind and the sequence
     * are two fields and {@code PgColumn.compareIdentity} reads both, so a branch
     * clearing one would leave a column that is not an identity still owning the
     * sequence of one.
     */
    @Test
    void aDroppedIdentityLeavesTheColumn() throws Exception {
        PgDatabase byAlter = load(table("c1 integer GENERATED ALWAYS AS IDENTITY") + """

                ALTER TABLE public.t ALTER COLUMN c1 DROP IDENTITY;""");
        PgColumn col = columnOf(byAlter, "c1");
        assertNull(col.getIdentityType(), "the dropped identity must leave the model");
        assertNull(col.getSequence(), "and take its sequence with it");

        String script = pipeline(load(table("c1 integer")), byAlter);
        assertEquals("", script.trim(),
                () -> "a column whose identity the file drops must equal one that never had it, got:\n" + script);
    }

    /** The other direction: against a database that still carries the identity. */
    @Test
    void aDroppedIdentityIsDroppedFromTheDatabase() throws Exception {
        String script = pipeline(load(table("c1 integer GENERATED ALWAYS AS IDENTITY")),
                load(table("c1 integer GENERATED ALWAYS AS IDENTITY") + """

                        ALTER TABLE public.t ALTER COLUMN c1 DROP IDENTITY;"""));
        assertEquals("""
                SET search_path = pg_catalog;

                ALTER TABLE public.t
                \tALTER COLUMN c1 DROP IDENTITY;""", script.trim());
    }

    // ------------------------------------------------------- alter_identity

    /**
     * The kind of the identity. Unread, the tool wrote {@code SET GENERATED
     * ALWAYS} against a database that already said {@code BY DEFAULT} - the exact
     * statement the file had just written, in reverse.
     */
    @Test
    void theKindOfTheIdentityStatedByAlterReachesTheModel() throws Exception {
        PgDatabase byAlter = load(table("c1 integer GENERATED ALWAYS AS IDENTITY") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET GENERATED BY DEFAULT;""");
        assertEquals("BY DEFAULT", columnOf(byAlter, "c1").getIdentityType(),
                "the kind the file states must be the kind the model carries");

        String script = pipeline(load(table("c1 integer GENERATED BY DEFAULT AS IDENTITY")), byAlter);
        assertEquals("", script.trim(),
                () -> "an identity kind written by ALTER must build the same column, got:\n" + script);
    }

    /** The other direction, which is the statement this tool writes itself. */
    @Test
    void theKindOfTheIdentityReachesTheDatabase() throws Exception {
        String script = pipeline(load(table("c1 integer GENERATED ALWAYS AS IDENTITY")),
                load(table("c1 integer GENERATED ALWAYS AS IDENTITY") + """

                        ALTER TABLE public.t ALTER COLUMN c1 SET GENERATED BY DEFAULT;"""));
        assertEquals("""
                SET search_path = pg_catalog;

                ALTER TABLE public.t
                \tALTER COLUMN c1 SET GENERATED BY DEFAULT;""", script.trim());
    }

    /**
     * An option of the underlying sequence, and the half that tells an alter from
     * a create: the statement names one option and the sequence keeps every other
     * one. Filling the sequence the way a {@code CREATE} fills it would reset the
     * cache this fixture states to the default, because a create starts from the
     * defaults and an alter starts from what is there.
     */
    @Test
    void aSequenceOptionStatedByAlterReachesTheModelAndKeepsTheRest() throws Exception {
        PgDatabase byAlter = load(table("c1 integer GENERATED ALWAYS AS IDENTITY (CACHE 7 MAXVALUE 100)") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET INCREMENT BY 5;""");
        PgDatabase inline = load(table(
                "c1 integer GENERATED ALWAYS AS IDENTITY (INCREMENT BY 5 CACHE 7 MAXVALUE 100)"));

        assertTrue(columnOf(inline, "c1").compare(columnOf(byAlter, "c1")),
                "the option the file states must land and the ones it does not must stay");
        String script = pipeline(inline, byAlter);
        assertEquals("", script.trim(),
                () -> "a sequence option written by ALTER must build the same sequence, got:\n" + script);
    }

    /**
     * The clause is {@code alter_identity+}, so one {@code ALTER COLUMN} may
     * carry several of these and every one of them has to land.
     */
    @Test
    void severalIdentityActionsInOneClauseAllLand() throws Exception {
        PgDatabase byAlter = load(table("c1 integer GENERATED ALWAYS AS IDENTITY") + """

                ALTER TABLE public.t ALTER COLUMN c1
                \tSET GENERATED BY DEFAULT SET INCREMENT BY 5 SET MAXVALUE 100;""");
        PgDatabase inline = load(table(
                "c1 integer GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 5 MAXVALUE 100)"));

        assertEquals("BY DEFAULT", columnOf(byAlter, "c1").getIdentityType());
        String script = pipeline(inline, byAlter);
        assertEquals("", script.trim(),
                () -> "every action of one clause must land, got:\n" + script);
    }

    /**
     * {@code NO MAXVALUE} is a value the statement states, not an option it fails
     * to mention - the difference an alter has to make and a create does not,
     * where a maximum left unsaid is simply the boundary of the type.
     */
    @Test
    void noMaxvalueStatedByAlterTakesTheMaximumAway() throws Exception {
        PgDatabase byAlter = load(table("c1 integer GENERATED ALWAYS AS IDENTITY (MAXVALUE 100)") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET NO MAXVALUE;""");
        PgDatabase inline = load(table("c1 integer GENERATED ALWAYS AS IDENTITY"));

        String script = pipeline(inline, byAlter);
        assertEquals("", script.trim(),
                () -> "NO MAXVALUE must take the maximum away, got:\n" + script);
    }

    /**
     * {@code RESTART} is not {@code START WITH}. It sets the value the sequence
     * is next to hand out, which is state of the database and not of the DDL -
     * the model has no field for it, and writing it into the start value would
     * put a number in the {@code CREATE} that the file never declared.
     */
    @Test
    void restartIsNotAStartValue() throws Exception {
        PgDatabase byAlter = load(table("c1 integer GENERATED ALWAYS AS IDENTITY") + """

                ALTER TABLE public.t ALTER COLUMN c1 RESTART WITH 100;""");
        PgDatabase inline = load(table("c1 integer GENERATED ALWAYS AS IDENTITY"));

        String script = pipeline(inline, byAlter);
        assertEquals("", script.trim(),
                () -> "RESTART states no part of the DDL, got:\n" + script);
    }

    /**
     * The column this clause does not speak for, and the reason it needs saying
     * twice. PostgreSQL refuses an identity action on a column that has no
     * identity - but leaving the guard out does more than accept illegal DDL: a
     * kind without a sequence is the very state that made
     * {@code PgAbstractTable.writeSequences} throw from {@code getQualifiedName},
     * so the file would load clean and the migration would fail.
     */
    @Test
    void anIdentityActionOnAPlainColumnIsLeftAlone() throws Exception {
        PgDatabase db = load(table("c1 integer") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET GENERATED BY DEFAULT SET INCREMENT BY 5;""");
        PgColumn col = columnOf(db, "c1");
        assertNull(col.getIdentityType(), "a column with no identity has no kind for this statement to change");
        assertNull(col.getSequence(), "and no sequence for it to write into");
        assertEquals("", pipeline(load(table("c1 integer")), db).trim(),
                "so the column stays the plain one the CREATE declared");
    }

    // ------------------------------------------------------ SET COMPRESSION

    /**
     * The compression method. Unread, the tool wrote {@code SET COMPRESSION
     * DEFAULT} against a database already carrying the method the file names.
     */
    @Test
    void theCompressionStatedByAlterReachesTheModel() throws Exception {
        PgDatabase byAlter = load(table("c1 text") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET COMPRESSION lz4;""");
        assertEquals("c1 text COMPRESSION lz4", columnOf(byAlter, "c1").getFullDefinition(),
                "the method the file states must be the one the DDL writes");

        String script = pipeline(load(table("c1 text COMPRESSION lz4")), byAlter);
        assertEquals("", script.trim(),
                () -> "a compression written by ALTER must build the same column, got:\n" + script);
    }

    /**
     * {@code DEFAULT} names the setting rather than a method, so it takes the
     * column's own method away - which is exactly the statement
     * {@code PgColumn.compareCompression} writes for a column that has none. Read
     * as a method it would put the word {@code DEFAULT} into a {@code CREATE}.
     */
    @Test
    void compressionDefaultTakesTheMethodAway() throws Exception {
        PgDatabase byAlter = load(table("c1 text COMPRESSION lz4") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET COMPRESSION DEFAULT;""");
        assertEquals("c1 text", columnOf(byAlter, "c1").getFullDefinition(),
                "the method must go, and no word must take its place");

        String script = pipeline(load(table("c1 text")), byAlter);
        assertEquals("", script.trim(),
                () -> "a column whose compression the file resets must equal one that never had it, got:\n" + script);
    }

    // --------------------------------------------------------- SET ENCODING

    /**
     * The Greenplum column encoding, which the tool writes itself: on a server it
     * recognises as Greenplum 7 {@code PgColumn.appendAlterSQL} emits
     * {@code ALTER COLUMN ... SET ENCODING (...)} for exactly this difference, so
     * leaving the clause unread meant a migration pgcodekeeper had generated
     * could not be read back into the project it came from.
     *
     * <p>
     * Only what the grammar and the model state is asserted here - the three
     * directives reach the three fields the inline {@code ENCODING} of a
     * {@code CREATE} fills. No Greenplum server was available to measure against.
     */
    @Test
    void theEncodingStatedByAlterReachesTheModel() throws Exception {
        PgDatabase byAlter = load(table("c1 text") + """

                ALTER TABLE public.t ALTER COLUMN c1
                \tSET ENCODING (COMPRESSTYPE=zlib, COMPRESSLEVEL=5, BLOCKSIZE=32768);""");
        assertEquals("c1 text ENCODING (COMPRESSTYPE = zlib, COMPRESSLEVEL = 5, BLOCKSIZE = 32768)",
                columnOf(byAlter, "c1").getFullDefinition(),
                "the three directives must reach the three fields the inline ENCODING fills");

        PgDatabase inline = load(table("c1 text ENCODING (COMPRESSTYPE=zlib, COMPRESSLEVEL=5, BLOCKSIZE=32768)"));
        assertTrue(columnOf(inline, "c1").compare(columnOf(byAlter, "c1")),
                "and the two spellings must build one column");
        String script = pipeline(inline, byAlter);
        assertEquals("", script.trim(),
                () -> "an encoding written by ALTER must build the same column, got:\n" + script);
    }

    // ------------------------------------------------------------ RESET (…)

    /**
     * The other half of the storage-parameter pair, whose {@code SET (...)} half
     * has had a writer all along. Unread, the tool proposed putting back the
     * parameter the file had reset - measured, {@code ALTER COLUMN c1 SET
     * (n_distinct=100)} against a database that no longer sets it.
     */
    @Test
    void aResetColumnOptionLeavesTheColumn() throws Exception {
        PgDatabase byAlter = load(table("c1 text") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET (n_distinct=100);

                ALTER TABLE public.t ALTER COLUMN c1 RESET (n_distinct);""");
        assertTrue(columnOf(byAlter, "c1").getOptions().isEmpty(),
                "the reset parameter must leave the model");

        String script = pipeline(load(table("c1 text")), byAlter);
        assertEquals("", script.trim(),
                () -> "a column whose parameter the file resets must equal one that never set it, got:\n" + script);
    }

    /** The other direction: against a database that still sets the parameter. */
    @Test
    void aResetColumnOptionReachesTheDatabase() throws Exception {
        String withOption = table("c1 text") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET (n_distinct=100);""";
        String script = pipeline(load(withOption), load(withOption + """


                ALTER TABLE public.t ALTER COLUMN c1 RESET (n_distinct);"""));
        assertEquals("""
                SET search_path = pg_catalog;

                ALTER TABLE ONLY public.t ALTER COLUMN c1 RESET (n_distinct);""", script.trim());
    }

    /**
     * The two halves have to build one key, so the reset goes through the very
     * call the {@code SET} half builds its own with - a key built by a second
     * route is a key that stops matching, and a reset that matches nothing is
     * silent by design, so the drift would show as the parameter simply staying.
     *
     * <p>
     * The name is deliberately written quoted, because that is the only place the
     * two routes can part - measured. An unquoted name reaches the parser already
     * folded to lower case, and {@code PgDiffUtils.getQuotedName} hands a
     * lower-case name straight back, so {@code n_distinct} and {@code N_Distinct}
     * alike end up as the key {@code n_distinct} by either route and nothing can
     * tell them apart. A quoted one is stored under its quoted spelling and only
     * the shared call produces it.
     *
     * <p>
     * What is asserted is that the two halves agree, not what the key they agree
     * on looks like, and not that a server would accept the parameter: the
     * spelling is the pre-existing behaviour of that call.
     *
     * <p>
     * The call is the column's own and not the table's: a column parameter has no
     * {@code toast.} namespace and no {@code OIDS} among its names, so the
     * table's {@code RESET} is the wrong twin to copy.
     */
    @Test
    void theTwoHalvesOfThePairBuildOneKey() throws Exception {
        PgDatabase byAlter = load(table("c1 text") + """

                ALTER TABLE public.t ALTER COLUMN c1 SET ("N_Distinct"=100);

                ALTER TABLE public.t ALTER COLUMN c1 RESET ("N_Distinct");""");
        assertTrue(columnOf(byAlter, "c1").getOptions().isEmpty(),
                () -> "the reset must find the key the SET built, got: " + columnOf(byAlter, "c1").getOptions());
    }

    /**
     * A name that matches nothing is left alone rather than reported, which is
     * the server's answer to the same statement.
     */
    @Test
    void aResetOptionTheColumnNeverSetIsSilent() throws Exception {
        var settings = new CoreSettings();
        PgDatabase db = new PgDumpLoader(() -> new ByteArrayInputStream(
                (table("c1 text") + """

                        ALTER TABLE public.t ALTER COLUMN c1 SET (n_distinct=100);

                        ALTER TABLE public.t ALTER COLUMN c1 RESET (n_distinct_inherited);""")
                        .getBytes(UTF_8)), "column property test", settings).load();
        assertTrue(settings.getErrors().isEmpty(),
                () -> "resetting a parameter that was never set raises nothing on the server either, got: "
                        + settings.getErrors());
        // quoted because that is the one spelling both sides of a comparison
        // reach: PgTablesReader reads pg_attribute.attoptions through
        // PgParserAbstract.fillOptionParams, which quotes a value that is not an
        // identifier, so a file stating it bare is read into the same text - see
        // PgParserAbstract.fillStorageParam. Measured on PostgreSQL 17.10, the
        // catalog stores {n_distinct=100} whether the statement writes 100 or
        // '100', so the two spellings are one value and only the quoted one is
        // reachable from both sides
        assertEquals("{n_distinct='100'}", columnOf(db, "c1").getOptions().toString(),
                "and the parameter the column does set must stay");
    }

    // ------------------------------------------------------------- fixtures

    /** A table whose second column is generated from its first. */
    private static String generated(String expression) {
        return table("c0 integer,\n\tc1 integer GENERATED ALWAYS AS (%s) STORED".formatted(expression));
    }

    private static String table(String body) {
        return """
                CREATE TABLE public.t (
                \t%s
                );""".formatted(body);
    }

    // -------------------------------------------------------------- helpers

    private static PgDatabase load(String sql) throws IOException, InterruptedException {
        var settings = new CoreSettings();
        PgDatabase db = new PgDumpLoader(() -> new ByteArrayInputStream(sql.getBytes(UTF_8)),
                "column property test", settings).load();
        assertTrue(settings.getErrors().isEmpty(),
                () -> "the fixture must load clean, got: " + settings.getErrors());
        return db;
    }

    private static PgAbstractTable tableOf(PgDatabase db) {
        PgSchema schema = (PgSchema) db.getSchema(SCHEMA);
        PgAbstractTable table = schema == null ? null : schema.getTable(TABLE);
        assertNotNull(table, "no table was parsed");
        return table;
    }

    private static PgColumn columnOf(PgDatabase db, String name) {
        return tableOf(db).getColumn(name);
    }

    private static String pipeline(PgDatabase oldDb, PgDatabase newDb) throws IOException, InterruptedException {
        return PgCodeKeeperApi.diff(new PgDatabaseProvider(), oldDb, newDb, new CoreSettings());
    }
}
