SET search_path = pg_catalog;

ALTER TABLE public."Tbl" RENAME TO "Tbl_randomly_generated_part";

ALTER SEQUENCE public."Tbl_Id_seq" RENAME TO "Tbl_Id_seq_randomly_generated_part";

ALTER SEQUENCE public."Tbl_user_seq" RENAME TO "Tbl_user_seq_randomly_generated_part";

ALTER SEQUENCE public."Tbl_O'Brien_seq" RENAME TO "Tbl_O'Brien_seq_randomly_generated_part";

CREATE TABLE public."Tbl" (
	"Id" integer NOT NULL,
	"user" integer NOT NULL,
	name22 text,
	"O'Brien" integer NOT NULL
);

ALTER TABLE public."Tbl" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
	SEQUENCE NAME public."Tbl_Id_seq"
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);

ALTER TABLE public."Tbl" ALTER COLUMN "user" ADD GENERATED BY DEFAULT AS IDENTITY (
	SEQUENCE NAME public."Tbl_user_seq"
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);

ALTER TABLE public."Tbl" ALTER COLUMN "O'Brien" ADD GENERATED BY DEFAULT AS IDENTITY (
	SEQUENCE NAME public."Tbl_O'Brien_seq"
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);

INSERT INTO public."Tbl"("Id", "user", name22, "O'Brien")
OVERRIDING SYSTEM VALUE
SELECT "Id", "user", name22, "O'Brien" FROM public."Tbl_randomly_generated_part";

DO LANGUAGE plpgsql $_$
DECLARE restart_var bigint = (SELECT COALESCE(
    (SELECT nextval(pg_get_serial_sequence('public."Tbl_randomly_generated_part"', 'Id'))),
    (SELECT MAX("Id") + 1 FROM public."Tbl"),
    1));
BEGIN
    EXECUTE $$ ALTER TABLE public."Tbl" ALTER COLUMN "Id" RESTART WITH $$ || restart_var || ';' ;
END
$_$;

DO LANGUAGE plpgsql $_$
DECLARE restart_var bigint = (SELECT COALESCE(
    (SELECT nextval(pg_get_serial_sequence('public."Tbl_randomly_generated_part"', 'user'))),
    (SELECT MAX("user") + 1 FROM public."Tbl"),
    1));
BEGIN
    EXECUTE $$ ALTER TABLE public."Tbl" ALTER COLUMN "user" RESTART WITH $$ || restart_var || ';' ;
END
$_$;

DO LANGUAGE plpgsql $_$
DECLARE restart_var bigint = (SELECT COALESCE(
    (SELECT nextval(pg_get_serial_sequence('public."Tbl_randomly_generated_part"', 'O''Brien'))),
    (SELECT MAX("O'Brien") + 1 FROM public."Tbl"),
    1));
BEGIN
    EXECUTE $$ ALTER TABLE public."Tbl" ALTER COLUMN "O'Brien" RESTART WITH $$ || restart_var || ';' ;
END
$_$;

DROP TABLE public."Tbl_randomly_generated_part";
